# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tools\gui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 270)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.b_termin_suchen = QtWidgets.QPushButton(self.centralwidget)
        self.b_termin_suchen.setAutoDefault(False)
        self.b_termin_suchen.setDefault(True)
        self.b_termin_suchen.setFlat(False)
        self.b_termin_suchen.setObjectName("b_termin_suchen")
        self.gridLayout.addWidget(self.b_termin_suchen, 6, 1, 1, 1)
        self.header_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.header_label.setFont(font)
        self.header_label.setAlignment(QtCore.Qt.AlignCenter)
        self.header_label.setObjectName("header_label")
        self.gridLayout.addWidget(self.header_label, 0, 0, 1, 2)
        self.b_code_generieren = QtWidgets.QPushButton(self.centralwidget)
        self.b_code_generieren.setObjectName("b_code_generieren")
        self.gridLayout.addWidget(self.b_code_generieren, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 1, 1, 1)
        self.pfad_layout = QtWidgets.QFormLayout()
        self.pfad_layout.setObjectName("pfad_layout")
        self.kontaktdaten_label = QtWidgets.QLabel(self.centralwidget)
        self.kontaktdaten_label.setObjectName("kontaktdaten_label")
        self.pfad_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.kontaktdaten_label)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.i_kontaktdaten_pfad = QtWidgets.QLineEdit(self.centralwidget)
        self.i_kontaktdaten_pfad.setObjectName("i_kontaktdaten_pfad")
        self.gridLayout_3.addWidget(self.i_kontaktdaten_pfad, 0, 0, 1, 1)
        self.b_dateien_kontaktdaten = QtWidgets.QPushButton(self.centralwidget)
        self.b_dateien_kontaktdaten.setObjectName("b_dateien_kontaktdaten")
        self.gridLayout_3.addWidget(self.b_dateien_kontaktdaten, 0, 1, 1, 1)
        self.pfad_layout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.gridLayout_3)
        self.zeitspanne_label = QtWidgets.QLabel(self.centralwidget)
        self.zeitspanne_label.setObjectName("zeitspanne_label")
        self.pfad_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.zeitspanne_label)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.b_dateien_zeitspanne = QtWidgets.QPushButton(self.centralwidget)
        self.b_dateien_zeitspanne.setObjectName("b_dateien_zeitspanne")
        self.gridLayout_4.addWidget(self.b_dateien_zeitspanne, 0, 1, 1, 1)
        self.pfad_layout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.gridLayout_4)
        self.gridLayout.addLayout(self.pfad_layout, 4, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 470, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "vaccipy"))
        self.b_termin_suchen.setText(_translate("MainWindow", "Termin suchen"))
        self.header_label.setText(_translate("MainWindow", "Vaccipy\n"
"\n"
"Willkommen bei der automatische Terminbuchung\n"
"für den Corona Impfterminservice "))
        self.b_code_generieren.setText(_translate("MainWindow", "Impf-Code generieren"))
        self.kontaktdaten_label.setText(_translate("MainWindow", "Pfad Kontakdaten:"))
        self.i_kontaktdaten_pfad.setText(_translate("MainWindow", "./data/kontaktdaten.json"))
        self.b_dateien_kontaktdaten.setText(_translate("MainWindow", "Dateien"))
        self.zeitspanne_label.setText(_translate("MainWindow", "Pfad Zeitspanne:"))
        self.lineEdit.setText(_translate("MainWindow", "./data/zeitspanne.json"))
        self.b_dateien_zeitspanne.setText(_translate("MainWindow", "Dateien"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
